# Generated by Django 5.2.8 on 2025-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="interested_course",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
